### ISSUE TITLE
你好 想请教下 如果是打印机没纸的情况，怎么处理呢？

### ISSUE THREAD

**Issue by RuiZhuo** [song940/node-escpos#100]
有方法可以获取到打印机的状态吗？

**Comment by Psychopoulet** [comment]
in english, please ?

**Comment by RuiZhuo** [comment]
oh sorry. my issue is , if the printer is no paper, how to do?

**Comment by song940** [comment]
@RuiZhuo escpos protocol only have one-way communition to terminal printer, 
but terminal's status LED will blink if no paper .

**Comment by ChimingPhang** [comment]
> @RuiZhuo escpos protocol only have one-way communition to terminal printer,
> but terminal's status LED will blink if no paper .

how can i detect the status of LED?

**Comment by ChimingPhang** [comment]
> @ChimingPhang No way.

OK，thank u
