### ISSUE TITLE
build: CircleCI setup

### ISSUE THREAD

**Issue by DanielRuf** [song940/node-escpos#104]
It seems it uses an old Node.js versions which produces some errors. We should also take a look at the other issues.

So far the tests are failing on the systems and not helpful for automatically testing PRs and commits and everything CI related.

**Comment by DanielRuf** [comment]
Travis can still not run the tests due to the libusb dependency which is not available on the testsystem(s) / VMs.

**Comment by DanielRuf** [comment]
> [song940](/song940) (Lsøng) closed this [3 minutes ago](#event-2177618328)

So far I see no changes / commits in the repo which fix this.
Is a PR welcome?

**Comment by song940** [comment]
@DanielRuf Oh! YES, I merged your PR, and thank you. 😄
