### ISSUE TITLE
Using for loop to print several orders after one another

### ISSUE THREAD

**Issue by OscarWoHA** [song940/node-escpos#107]
I simply do not understand why this code prints out the same order twice, instead of printing separate orders? I've been trying different approaches for a couple of days now, but cannot wrap my head around it. 

Here's a gist with the code used..
https://gist.github.com/OscarWoHA/0055c9bf745c537d86865447222c4196

**Comment by Psychopoulet** [comment]
maybe because you use it in a synchrone way. try to wait until the end of the "close" event (which flush the buffer) before allow new sending, to avoid multiple send to the printer

**Comment by song940** [comment]
Any questions ?
