### ISSUE TITLE
The system cannot find message text

### ISSUE THREAD

**Issue by diegopavani1** [song940/node-escpos#114]
Platform: Windows 7 Ultimate 64 Bits. 8gb.

Error: The system cannot find message text for message number 0x%1 in the message file for %2

Details:  
![erro escpos](https://user-images.githubusercontent.com/13602014/37249220-1a4b3620-24c2-11e8-8aea-8ea8e9608296.png)

**Comment by Psychopoulet** [comment]
ok.

**Comment by devyaz** [comment]
Has anyone found  solution to this ? it doesn work in Electron only if you do ```node somefile``` or the examples in escpos folder

**Comment by Psychopoulet** [comment]
see #139
