### ISSUE TITLE
can find the device and input the text,but not output anything

### ISSUE THREAD

**Issue by LorneZH** [song940/node-escpos#116]
![image](https://user-images.githubusercontent.com/24568396/37509320-d1bea634-2931-11e8-8159-6cf15189d263.png)

**Comment by risleylima** [comment]
You have to call the flush() function to send data to the printer. Right after the cut() function.

**Comment by Psychopoulet** [comment]
or you just read the actual one, see that "close" is an asynchronous function and use it properly...
