### ISSUE TITLE
Windows下打印机 Error:LIBUSB_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by onewayxp** [song940/node-escpos#12]
1-https://github.com/tessel/node-usb

Windows

Use Zadig to install the WinUSB driver for your USB device. Otherwise you will get LIBUSB_ERROR_NOT_SUPPORTED when attempting to open devices.

http://zadig.akeo.ie/
下载安装

2-http://zadig.akeo.ie/
下载安装配置好驱动之后
isKernelDriverActive 
Error:LIBUSB_ERROR_NOT_SUPPORTED

参考：
http://libusb.sourceforge.net/api-1.0/group__dev.html

int libusb_detach_kernel_driver ( libusb_device_handle \* dev,
int interface_number 
)

This functionality is not available on Darwin or Windows.
LIBUSB_ERROR_NOT_SUPPORTED on platforms where the functionality is not available

下面79行需要手工修改：【if(iface.isKernelDriverActive()){】放到try里面
https://github.com/song940/node-escpos/blob/master/adapter/usb.js

if(iface.isKernelDriverActive()){
try{
iface.detachKernelDriver();
}catch(e){
console.error("[ERROR] Could not detatch kernel driver: %s", e)
}
}

**Comment by song940** [comment]
@onewayxp Did you solve the problem ?
