### ISSUE TITLE
Is it possible to print from external server to my client printer.

### ISSUE THREAD

**Issue by Adarshjayan3032** [song940/node-escpos#125]
I am planning to design a web based pos system so this code will be serving on some external cloud server. So is it possible to print receipt from webpage hosted in web server ? If the printer is not reachable to server, can you suggest some external libraries for pairing with node js component.

**Comment by jor3l** [comment]
Socket on the Server, local computer connected to that socket with Access to the printer

**Comment by song940** [comment]
@Adarshjayan3032 please ref pull-request https://github.com/song940/node-escpos/pull/78
