### ISSUE TITLE
"ERROR TypeError: Buffer is not a constructor" when trying to create printer object

### ISSUE THREAD

**Issue by u2633** [song940/node-escpos#126]
![capture](https://user-images.githubusercontent.com/27126539/39565225-c31fa2a8-4ee9-11e8-8f0c-01c4c20f358c.PNG)

node version: 8.11.1
npm version : 5.6.0

Is there any one who has the same issue like me!?

**Comment by Psychopoulet** [comment]
normal. new Buffer() must not be used, it's deprecated. we should use Buffer.from() instead.

**Comment by Psychopoulet** [comment]
https://github.com/song940/node-escpos/pull/127

**Comment by u2633** [comment]
👍

**Comment by u2633** [comment]
@Psychopoulet 
Thanks. In my case, "new Buffer()" can still work in my develop build, but failed 
 on production build.

**Comment by song940** [comment]
emm, We depend a package named [mutable-buffer](https://www.npmjs.com/package/mutable-buffer) and that publish a Incompatible version ...

**Comment by song940** [comment]
Have you log "Buffer" object in console ?
and  mutable-buffer version ?

**Comment by u2633** [comment]
@song940 thanks for your quick reply.

yes, I have tried to log that, the result as below:
![capture](https://user-images.githubusercontent.com/27126539/39573459-e0952e2c-4f05-11e8-9ae3-549e5ad25a38.PNG)

I found that mutable-buffer version is still 2.1.1 on your project, but I have tried to override the version to 2.0.3 in my pakages.json. 

I'm using electron and angular these two frameworks and using angular CLI as the compiler then packages my project by using [electron-builder](https://github.com/electron-userland/electron-builder)

**Comment by Psychopoulet** [comment]
mutable-buffer...
woops, sorry guys, not enougth coffe I guess ><

**Comment by song940** [comment]
@u2633 i tried fix that issue again, it works on my terminal printer .

**Comment by u2633** [comment]
Thanks guys, I also debug with my project and It finally works! I found something interesting about buffer flush. I used to call cut() method at the end of print process, and it would do flush before, however I have to use flush() at present. Anyway, it is really such a good experience to me.
