### ISSUE TITLE
关于barcode打印不同长度的问题

### ISSUE THREAD

**Issue by rplees** [song940/node-escpos#140]
你好,试用了项目的打印,很方便的进行打印的格式化,但我在用到barcode的时候遇到了个问题想寻求解决方法,使用例子里的 `EAN13`, `EAN8` 格式打印<=12和<=7的长度是正常的且能让扫码枪识别(我的扫码枪是在淘宝上买的一款), 然而当我准备打印30长度以内(比如订单号)的条形码时,我在 `command.js`的`_.BARCODE_FORMAT`看已经定义的挨个试,用`UPC-A`格式可以显示出条形码,但扫码枪扫不出内容来,其他的格式我都试过了,条形码那一栏是空白的,请问有什么解决方法吗? 谢谢

ps:我用的打印机是58mm的Xprinter

**Comment by Psychopoulet** [comment]
please use english to question us

**Comment by song940** [comment]
Any questions here?
