### ISSUE TITLE
Image exemple incomplete

### ISSUE THREAD

**Issue by Xsmael** [song940/node-escpos#146]
I've tried the example at `node-escpos/examples/image.js`

```
const escpos = require('escpos');
const device  = new escpos.USB(0x456,0x808);
const options = { encoding: "GB18030" /* default */ };
// encoding is optional
 
const printer = new escpos.Printer(device, options); 
 
escpos.Image.load(__dirname + 'tux.png', function(image){

  device.open(function(){

    printer
    .align('ct')

    .image(image, 's8')
    .image(image, 'd8')
    .image(image, 's24')
    .image(image, 'd24')
    
    .raster(image)
    .raster(image, 'dw')
    .raster(image, 'dh')
    .raster(image, 'dwdh')
    .cut();
  });
});
```

But when i ruin this, absolutely nothing happens, and the cli (node) do not return.

What could be the problem ?

**Comment by Psychopoulet** [comment]
__dirname + 'tux.png'
don't you this you missed something ? ^^

try __dirname + '/tux.png (like in the doc), or better and os agnostic : require('path').join(__dirname, 'tux.png');

**Comment by Psychopoulet** [comment]
of course, if you don't have a picture named tux.png in the current directory you are in, there will be no picture to load...

**Comment by Xsmael** [comment]
I downloaded the exact same tux.png and kept it in the same directory than my nodejs script.
I removed __dirname , because the image was in the same directory.

**Comment by Psychopoulet** [comment]
__dirname + 'tux.png' => "directorytux.png"
__dirname + '/tux.png => "directory/tux.png"
require('path').join(__dirname, 'tux.png') => "directory/tux.png" | "directory\tux.png" (depend on your system)

if you remove the __dirname and you does not set the wanted directory in your terminal, you obviously will not load the file

**Comment by Psychopoulet** [comment]
do you know the "cd" command (linux, mac & windows) ?

**Comment by Xsmael** [comment]
yes

**Comment by Xsmael** [comment]
`escpos.Image.load('./tux.png', function(image)`  this is  what i wrote and, by the way, when i put a wrong path (intentionnally)   i get this error:

> C:\node\thermalPrint\node_modules\escpos\printer.js:493
>     throw new TypeError('Only escpos.Image supported');
>     ^
> 
> TypeError: Only escpos.Image supported
>     at Printer.image (C:\node\thermalPrint\node_modules\escpos\printer.js:493:11)
>     at C:\node\thermalPrint\image.js:15:6
>     at Interface.<anonymous> (C:\node\thermalPrint\node_modules\escpos\adapter\usb.js:123:23)
>     at Device.<anonymous> (C:\node\thermalPrint\node_modules\usb\usb.js:239:6)
>

**Comment by Psychopoulet** [comment]
that's it. use it to set the terminal into this directory if you don't use __dirname command.
if you use __dirname, use it with a separator beetween it and the file (path.join or simple "/" one)

**Comment by Xsmael** [comment]
okay, this is the path to my project directory `C:\node\thermalPrint`
in there, i have image.js and tux.png, 

here is my CLI output:
![image](https://user-images.githubusercontent.com/7417007/43795546-50560684-9a9f-11e8-9e15-eff3c429b418.png)


as you can see, nothig happens, it doesnt return, and the printer doesnt react.

did i do anything wrong here ?

**Comment by Xsmael** [comment]
also i notice that if instead of `./tux.png` i write a filename that doesn exist, i get this error: 
![image](https://user-images.githubusercontent.com/7417007/43795719-da9033e2-9a9f-11e8-8a25-8ed045178afc.png)

so ithink, that, maybe it finds the image file but something else bugs, cause in case the path is correct no errors, but no output

**Comment by Xsmael** [comment]
damn it!    i just realilse, that  ` .close()` was missing sorry for all this, it will really reallly really be good if the example are working exmaple, it'll save us abit of time.
Thanks for all.

**Comment by Psychopoulet** [comment]
thanks to you for pointing an example failure ! I reopen that thread
