### ISSUE TITLE
Use with VueJS?

### ISSUE THREAD

**Issue by Wolrab1** [song940/node-escpos#150]
Apologies for my naivety.

I'm building an application in VueJS and potentially ElectronJS and I wish to use a plugin that allows me to print directly to a connect printer by specifying the VID etc. 

I've setup a dummy project with VueJs and installed this package. I've then in my vue file called the package following the instructions.

```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";

window.escpos = require("escpos");

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");
```

When serving this application I then get the error: 

> Uncaught TypeError: Cannot read property '_handle' of undefined

This is know doubt due to my lack of knowledge with packages outside of Vue plugins but I thought I would reach out.

**Comment by saintplay** [comment]
this package is intended to run inside Node.js, yo can't  run it inside a browser,
