### ISSUE TITLE
Inconsistent flush of image

### ISSUE THREAD

**Issue by ograva** [song940/node-escpos#152]
I'm having trouble getting images, a logo image and a QR Image,  to flush completely. 

It works the first time after the printer is reset.  

Then as I try it a second time it just stops midway during the flush for the QR code image and does not proceed to close. 

When I run the same program again without resetting the printer I get the following error.

Can't close device with a pending request

Here is snippet of my code 

`device.open(function(){
    printer
       .font('A')
      .align('ct')
      .image(logo_image, 'd24')
      .flush()
      .text("ok")
      .image(qrimage, 'd24')
      .flush()
      .text("ok")
      .close()
    });`

**Comment by Psychopoulet** [comment]
you can use flush's callback to be sure the operation is done, before execute the next one

**Comment by Psychopoulet** [comment]
printer.flush(() => {
// your code
});

**Comment by song940** [comment]
Any questions?
