### ISSUE TITLE
How to run on nw.js

### ISSUE THREAD

**Issue by Sun-Traget** [song940/node-escpos#155]
How to run on nw.js

**Comment by Psychopoulet** [comment]
like any package ?

**Comment by pannysp** [comment]
it's my blog，that's all.
https://www.cnblogs.com/pannysp/p/9687743.html

**Comment by song940** [comment]
duplicate with https://github.com/song940/node-escpos/issues/180 https://github.com/song940/node-escpos/issues/150 https://github.com/song940/node-escpos/issues/196 https://github.com/song940/node-escpos/issues/76
