### ISSUE TITLE
my printer can't print qrcode

### ISSUE THREAD

**Issue by juransaber** [song940/node-escpos#163]
/**
 * [print qrcode image]
 * @param  {[type]}   content  [description]
 * @param  {[type]}   options  [description]
 * @param  {[Function]} callback [description]
 * @return {[Printer]} printer  [the escpos printer instance]
 */
Printer.prototype.qrimage = function (content, options, callback) {
  var self = this;
  if (typeof options == 'function') {
    callback = options;
    options = null;
  }
  options = options || { type: 'png', mode: 'dhdw' };
  var buffer = qr.imageSync(content, options);
  var type = ['image', options.type].join('/');
  getPixels(buffer, type, function (err, pixels) {
    if (err) return callback && callback(err);
    self.raster(new Image(pixels), options.mode);
    callback && callback.call(self, null, self);
  });
  return this;
}; 

line: 479      self.raster(new Image(pixels), options.mode);
must change to:
self.image(new Image(pixels), options.mode);

**Comment by Psychopoulet** [comment]
reason ? context ?

**Comment by MLDMoritz** [comment]
This works :-)
