### ISSUE TITLE
qrCode exceed the paper

### ISSUE THREAD

**Issue by Tina931010** [song940/node-escpos#166]
![image](https://user-images.githubusercontent.com/26641060/47976154-10967680-e0ec-11e8-8b23-9a9447bffc58.png)
like this. The code image is not completed. The right part got lost.
It should be like 
![image](https://user-images.githubusercontent.com/26641060/47976198-44719c00-e0ec-11e8-8c71-18947547ee34.png)
How can I solve it?

**Comment by Tina931010** [comment]
try this url 'http://im.gouyaoqu.com/qr/scan?qrCode=498bfad481ca43f5a4e99a1a40923533&type=DRUGSTORE_ORDER'

**Comment by Tina931010** [comment]
device.open(function(){
    printer
      .qrimage('http://im.gouyaoqu.com/qr/scan?qrCode=498bfad481ca43f5a4e99a1a40923533&type=DRUGSTORE_ORDER', function(err){
        this.cut();
        this.close();
      })
  });

**Comment by rafaelcardos0** [comment]
You can resize the QRCode image passing some options to qrimage method (second parameter).
Your code should looke like this:

`
device.open(function(){
	printer
		.qrimage('http://im.gouyaoqu.com/qr/scanqrCode=498bfad481ca43f5a4e99a1a40923533&type=DRUGSTORE_ORDER', { type: 'png', mode: 'dhdw', size: 4 }, function(err){
		this.cut();
		this.close();
	})
});
`

The default size is 5, try 4 or 3.

**Comment by mladen-babic** [comment]
There is no "size" parameter in the options object !!!

**Comment by Psychopoulet** [comment]
of course there is a "size" option !!
it's transfered to the "imageSync" method of the "qr-image" package

**Comment by Psychopoulet** [comment]
there is a doc point, BTW.

**Comment by stevetsim** [comment]
> of course there is a "size" option !!
> it's transfered to the "imageSync" method of the "qr-image" package

`qrimage(content: string, options?: { type: string; mode: string }, callback?: (error: Error | null, printer?: Printer) => void): Printer;`

Actually, there is no "size" parameter in the options object as you can see above. So, how can I control the size of the qrcode?

**Comment by ThayllanFelipe** [comment]
this doesn't work in typescript

**Comment by abdulkholiqmahcoo-ux** [comment]
> ![image](https://user-images.githubusercontent.com/26641060/47976154-10967680-e0ec-11e8-8b23-9a9447bffc58.png) like this. The code image is not completed. The right part got lost. It should be like ![image](https://user-images.githubusercontent.com/26641060/47976198-44719c00-e0ec-11e8-8c71-18947547ee34.png) How can I solve it?

**Comment by fatimaajaz015-ctrl** [comment]
How can i solve

**Comment by catalandaniel983-cpu** [comment]
pls open my qrcode sg lisinse of sosia.
