### ISSUE TITLE
My printer prints qrimage without cutting paper.

### ISSUE THREAD

**Issue by flyFash** [song940/node-escpos#169]
When printing a qrimage, the printer sometimes cuts paper and sometimes does not cut it.When the paper is not cut, the method is executed, but the buffer.write method seems to have not been executed.
`this.printer.align("ct").qrimage(qrcodeUrl, function (err) {
       this.cut();
       this.close();
  });`
Everything is normal without printing the qrimage.

**Comment by Psychopoulet** [comment]
use callbacks

**Comment by rafaelcardos0** [comment]
What is your printer brand and model?

**Comment by iYaroslav** [comment]
Same issue.
Printer VKP80II.
This printer has a command `eject`, it must be called immediately after the `cut`
Command: `GS e 3 0`

**Comment by Psychopoulet** [comment]
probably because you didn't use "cut" method ? or correctly use callbacks ? without any context, it's a closed issue...

**Comment by Psychopoulet** [comment]
probably because of a bad use of callback, or a missing "cut" method.
there is no context here...

**Comment by Psychopoulet** [comment]
use callbacks, like
print("test", (err) => {
return err ? console.log(err) :  cut ((err) => {
console.log(err);
close();
})
});

**Comment by iYaroslav** [comment]
``` js
/**
 * [function Cut paper]
 * @param  {[type]} part [description]
 * @return {[Printer]} printer  [the escpos printer instance]
 */
Printer.prototype.cut = function (part, feed) {
  this.feed(feed || 3);
  this.buffer.write(_.PAPER[
    part ? 'PAPER_PART_CUT' : 'PAPER_FULL_CUT'
  ]);
  return this;
};
```

Method `cut` not support callbacks
Or I do not understand something?

**Comment by rokobuljan** [comment]
After ages... Managed to cut (on NP 2411 D) using

```js

printer
  .align("ct")
  .text("TEST!")
  .raw(Buffer.from([0x1B, 0x64, 0x03, 0x1B, 0x6D]))
  .close();
```

Some other codes you could try:

```js
  .raw(Buffer.from([0x1D, 0x56, 0x42, 0x03])) // GS V B - Full cut with feed
  .raw(Buffer.from([0x1D, 0x56, 0x41, 0x03])) // GS V A - Partial cut with feed
  .raw(Buffer.from([0x1D, 0x56, 0x30])) // GS V 0 - Full cut
  .raw(Buffer.from([0x1D, 0x56, 0x31])) // GS V 1 - Partial cut   
  .raw(Buffer.from([0x1B, 0x64, 0x03, 0x1B, 0x6D])) // // Feed 3 lines then cut <<< I used this one for a partial cut
```

PS: don't be scared to try them all at once, and then see which one worked (if any at all).
