### ISSUE TITLE
Can someone recommend 58mm-printer that can fit this package

### ISSUE THREAD

**Issue by jarheadjoe** [song940/node-escpos#179]

**Comment by jor3l** [comment]
Any epson printer should work, even the chinese ones that cost about 25$ work also:
[https://www.amazon.com/TEROW-Portable-Printing-Compatible-Commands/dp/B07848ZBXT/ref=sr_1_19?ie=UTF8&qid=1550074511&sr=8-19&keywords=thermal+printer](https://www.amazon.com/TEROW-Portable-Printing-Compatible-Commands/dp/B07848ZBXT/ref=sr_1_19?ie=UTF8&qid=1550074511&sr=8-19&keywords=thermal+printer)
