### ISSUE TITLE
Use it in a browser

### ISSUE THREAD

**Issue by jarheadjoe** [song940/node-escpos#180]
Hi guys, someone try to use this package in browser using webpack/browserify? Or maybe it can't work in browser because it need to access the hardware?

**Comment by Psychopoulet** [comment]
it's not designed to be used in a browser, but you can use the microserver embeded

**Comment by jor3l** [comment]
The printer / comms do work in a browser, I think it is possible to create an adapter for both USB and BLE printers (I have done this but not using this as a package)

**Comment by song940** [comment]
duplicate with https://github.com/song940/node-escpos/issues/180 https://github.com/song940/node-escpos/issues/150 https://github.com/song940/node-escpos/issues/196 https://github.com/song940/node-escpos/issues/76
