### ISSUE TITLE
how to print columns or table

### ISSUE THREAD

**Issue by netico14** [song940/node-escpos#182]
Hello, i need to print a table with 4 columns without lines, can i use this plugin for that?, thanks

**Comment by Psychopoulet** [comment]
ok.
you can use this module (of course not in a front project), you just have to decide first how many characters the printer support, then divide in columns your data and autocomplete with blank spaces (before or after for alignement).

example : if the printer support 42 characters / line :

42 / 4 = 10,5 = 10 (you have to calculate this BEFORE and not for each line)

"test" "test2" "column" "column2" becomes
"test" (4 characters) => "test      "
"test2" (5 characters) => "test2     "
"column" (6 characters) => "column    "
"column2" (7 characters) => "column2   "

**Comment by Psychopoulet** [comment]
... of course, github remove multiple blank spaces ><
so, "test" have (10 - 4 characters = 6) blank spaces,
etc...

**Comment by netico14** [comment]
Many thanks for the answer, the problem is that the text is dinamic, from
bbdd

**Comment by Psychopoulet** [comment]
so, you have to compute it with break lines, but the process is still the same

**Comment by netico14** [comment]
Great, thank you very much
