### ISSUE TITLE
win10 node-gyp rebuild error

### ISSUE THREAD

**Issue by shuihuasheng** [song940/node-escpos#185]
D:\node-port> npm install escpos

> @serialport/bindings@2.0.6 install D:\node-port\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.14.2 runtime=node arch=x64 platform=win32)

D:\收银台\收银台--zjh\node-port\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir va
riable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [D:\收银台\收银台--zjh\node-port\n
ode_modules\@serialport\bindings\build\bindings.vcxproj]
  TRACKER : 错误 TRK0005: 未能找到: “CL.exe”。系统找不到指定的文件。

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(355,5): error MSB6006: “CL.exe”已退出，代码为 5。 [D:\
收银台\收银台--
zjh\node-port\node_modules\@serialport\bindings\build\bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\node-port\node_modules\@serialport\bindings
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> usb@1.5.0 install D:\node-port\node_modules\usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[usb] Success: "D:\node-port\node_modules\usb\src\binding\usb_bindings.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN node-port@1.0.0 No description
npm WARN node-port@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@2.0.6 (node_modules\@serialport\bindings):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @serialport/bindings@2.0.6 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ escpos@2.4.10
added 141 packages from 116 contributors and audited 327 packages in 17.156s
found 0 vulnerabilities

**Comment by Psychopoulet** [comment]
like it's written in the logs, it's a serialport's issue...
probably caused by the node-gyp package, certainly because of a wrong setup.
