### ISSUE TITLE
Can set text alignment or create table layout

### ISSUE THREAD

**Issue by siteslave** [song940/node-escpos#190]
Can set text alignment like this.

```
printer.leftRight("Left", "Right"); 
printer.table(["One", "Two", "Three"]);

printer.tableCustom([ 
  { text:"Left", align:"LEFT", width:0.5 },
  { text:"Center", align:"CENTER", width:0.25, bold:true },
  { text:"Right", align:"RIGHT", width:0.25 }
]);

```

demo code from [https://www.npmjs.com/package/node-thermal-printer](https://www.npmjs.com/package/node-thermal-printer)

**Comment by Psychopoulet** [comment]
you have all the tools to wrap it anyway... that's I do, with XML parser to create a basic API
you cannot create "table" method" without knowing the printer's max characters/line

**Comment by song940** [comment]
Any questions?

**Comment by brkrtp** [comment]
> printer's

Can you send example code?

**Comment by Psychopoulet** [comment]
simple html parser and some loops for autocomplete columns with spaces, with a predetermined width (42 chars by default)
