### ISSUE TITLE
Print output to PDF or something.

### ISSUE THREAD

**Issue by zeoliveirajunior** [song940/node-escpos#191]
Hello,

Is there anyway, just for testing, to print the output in a PDF file or something like that?

**Comment by Psychopoulet** [comment]
you can convert it into picture, then print the picture
https://www.npmjs.com/package/pdf-image
https://www.npmjs.com/package/pdf2pic

**Comment by Psychopoulet** [comment]
Ow, sorry, I misunderstood. I thought you want to print a pdf ><
... hem, I'm sorry but the answer is still no
