### ISSUE TITLE
use this module with laravel mix

### ISSUE THREAD

**Issue by farshadfahimi1371** [song940/node-escpos#195]
when I'm use this module on compile the example code get the below error

`ERROR in ./node_modules/request/node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/var/www/toobasalon/private/node_modules/request/node_modules/tunnel-agent'
 @ ./node_modules/request/node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/node-pre-gyp/lib/install.js
 @ ./node_modules/node-pre-gyp/lib ^\.\/.*$
 @ ./node_modules/node-pre-gyp/lib/node-pre-gyp.js
 @ ./node_modules/usb/usb.js
 @ ./node_modules/escpos/adapter/usb.js
 @ ./node_modules/escpos/index.js
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/user/Profile.vue
 @ ./resources/assets/js/components/user/Profile.vue
 @ ./resources/assets/js/admin.js
 @ multi ./resources/assets/js/admin.js`

what is the reason and how solve this

**Comment by Psychopoulet** [comment]
context ? node version ? native/electron/nw ?
"Module not found: Error: Can't resolve 'tls'" ... => npm install tls ?
