### ISSUE TITLE
Can I use this with ReactJS?

### ISSUE THREAD

**Issue by SAngelCuadrosV** [song940/node-escpos#196]
Hi, I'm trying to use an USB Printer and wanna print when I click on a button.
I'm Using "create-react-app" to create de basic proyect and include the dependencies, but when I try to print  got a lot of errors with "node-pre-gyp" and "aws-sdk", so I installed both dependencies and try again but got these errors:

`
TypeError: Error.captureStackTrace is not a function
getFileName
C:\imprimir\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\imprimir\node_modules\bindings\bindings.js:135

  132 | }; // run the 'prepareStackTrace' function above
  133 | 
  134 | 
> 135 | Error.captureStackTrace(dummy);
      | ^  136 | dummy.stack; // cleanup
  137 | 
  138 | Error.prepareStackTrace = origPST;

bindings
C:\imprimir\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\imprimir\node_modules\bindings\bindings.js:59

  56 | }); // Get the module root
  57 | 
  58 | if (!opts.module_root) {
> 59 |   opts.module_root = exports.getRoot(exports.getFileName());
     | ^  60 | } // Ensure the given bindings name ends with .node
  61 | 
  62 | 

(anonymous function)
C:\imprimir\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\imprimir\node_modules\serialport\lib\index.js:3

  1 | var SerialPort = require('@serialport/stream');
  2 | 
> 3 | var Binding = require('@serialport/bindings');
  4 | 
  5 | var parsers = require('./parsers');
  6 | /**

(anonymous function)
C:\imprimir\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\imprimir\node_modules\escpos\adapter\serial.js:7

   4 | 
   5 | var EventEmitter = require('events');
   6 | 
>  7 | var SerialPort = require('serialport');
   8 | /**
   9 |  * SerialPort device
  10 |  * @param {[type]} port

(anonymous function)
C:\imprimir\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\imprimir\node_modules\escpos\index.js:7

   4 |  */
   5 | 
   6 | exports.USB = require('./adapter/usb');
>  7 | exports.Serial = require('./adapter/serial');
   8 | exports.Network = require('./adapter/network');
   9 | exports.Console = require('./adapter/console');
  10 | /**
`

**Comment by Psychopoulet** [comment]
... do you mean react native ? 'cause it's not designed to work in a browser stack.
you can create your own adaptator or use it as a micro-server localy
