### ISSUE TITLE
Does this package works with react native?

### ISSUE THREAD

**Issue by shubhamdeol** [song940/node-escpos#197]

**Comment by song940** [comment]
This library is not designed for browser stack, but you can use network adapter to connect printer.

**Comment by jor3l** [comment]
worth to mention, you can use a usb printer with it by creating a custom adapter as well

**Comment by Psychopoulet** [comment]
he ask a question about react NATIVE, which is not designed for browser but for mobile.
IDK if it works with it, but I guess it should (with network adapter for example) ? should be tested.

**Comment by jor3l** [comment]
My bad, not an easy test imo but it could work, considering many of the dependencies get to work with react native

**Comment by shubhamdeol** [comment]
I really don't have any idea about how network adapter works with react native.  Please someone explain widely.

**Comment by Psychopoulet** [comment]
it's just a basic socket wrapper for nodejs, so it should works
https://github.com/song940/node-escpos/blob/master/adapter/network.js
