### ISSUE TITLE
The "images.js" in "examples" can not run.

### ISSUE THREAD

**Issue by ycy0312** [song940/node-escpos#203]
I tried the "images.js" in "examples" but it could not run successfully.
![image](https://user-images.githubusercontent.com/22163837/55700169-d31e7800-5a00-11e9-8976-ebb7ba69e8bf.png)

**Comment by Psychopoulet** [comment]
... can we have a little context, please ?
OS ? node version ? code used ? etc...

**Comment by mbrodt** [comment]
Not OP, but I'm having the same issue. Running node v10.15.3 on macOS Mojave 10.14.3.

Code here:

`const device = new escpos.USB()
  const options = { encoding: 'GB18030' /* default */ }
  const printer = new escpos.Printer(device, options)

  const tux = path.join(__dirname, 'tux.png')
  escpos.Image.load(tux, function(image) {
    device.open(function() {
      printer
        .image(image, 's8')
        .image(image, 'd8')
        .image(image, 's24')
        .image(image, 'd24')
        .raster(image)
        .raster(image, 'dw')
        .raster(image, 'dh')
        .raster(image, 'dwdh')

        .cut()
        .close()
    })
  })`

The tux is in the right place, and the error is the exact same as OP's.

Any help is appreciated!

**Comment by ycy0312** [comment]
Sorry...My fault.
OS：windows 10
node version：v8.9.3
Code is same as the example.
![image](https://user-images.githubusercontent.com/22163837/55767318-ed149500-5aaa-11e9-8106-a6334ee37853.png)

**Comment by jor3l** [comment]
Can you guys try that example without the chaining? ( put a printer on each line)

**Comment by mbrodt** [comment]
Tried that, same issue. Also tried a simple printer.image(image, 's8').cut().close(), but the error stays the same.

**Comment by song940** [comment]
Because [printer#image](https://github.com/song940/node-escpos/blob/master/printer.js#L491) is async function, so you can not chaining.

**Comment by mbrodt** [comment]
That does it. Thanks a lot guys!
