### ISSUE TITLE
Print on another port other than the 9100

### ISSUE THREAD

**Issue by nmorales1991** [song940/node-escpos#205]
Hi. Can I print on another port other than the 9100?

**Comment by song940** [comment]
```js
const device  = new escpos.Network('localhost', 9200); // <-- You can change the port
const printer = new escpos.Printer(device);
```

**Comment by nmorales1991** [comment]
> ```js
> const device  = new escpos.Network('localhost', 9200); // <-- You can change the port
> const printer = new escpos.Printer(device);
> ```

But do you have to configure something else? since with any other port I get an error

**Comment by Psychopoulet** [comment]
the IP ? I guess the printer is not on localhost...

**Comment by nmorales1991** [comment]
> the IP ? I guess the printer is not on localhost...

Is a Network Connection to other ip, is not localhost.
Then if it is to another ip, can not be with another port?

**Comment by Psychopoulet** [comment]
... what ?

**Comment by nmorales1991** [comment]
> ... what ?

The printer is not localhost. Is a network connection to other ip . This works only with the port 9100

`const device  = new escpos.Network('ip printer', 9100);`

But with any other port it does not work

**Comment by Psychopoulet** [comment]
you does not have control on port's change, so you can change it without problem.
If the changed port does not work, you should try to telnet it because you probably try an inexistant IP/port combinaison
