### ISSUE TITLE
Example for Screen device

### ISSUE THREAD

**Issue by Tauri28** [song940/node-escpos#206]
I get "CONNECTED" and "CLOSED" but screen remains blank. Am I missing something? I am using Epson DM-D30.

```
import * as escpos from "escpos";
const device = new escpos.USB(0x04B8, 0x0202);
const screen = new escpos.Screen(device);
device.open((err) => {
	if (err) throw err;
	console.log("CONNECTED");
	screen.moveHome();
	screen.text("Hello!", "utf8");
	screen.close(() => {
		console.log("CLOSED");
	});
});
```

**Comment by song940** [comment]
Maybe @atiertant can help you.

**Comment by nicolasbadia** [comment]
Same problem here. Nothing is happening.

**Comment by atiertant** [comment]
@Tauri28 i tryed on Linux with oxhoo AF240U.
it required configure device to esc/pos and use minicom to use serial port.

**Comment by nicolasbadia** [comment]
For the record, after connecting the display directly to the computer and getting the ID with `lsusb`, everything worked.

`lsusb`:
```
Bus 001 Device 004: ID 1504:008c
```

JS:
```
const device = new escpos.USB(0x1504, 0x008c);
const screen = new escpos.Screen(device);
```
