### ISSUE TITLE
TypeError: Cannot read property 'transfer' of undefined at USB.write (Windows 7)

### ISSUE THREAD

**Issue by Canser** [song940/node-escpos#21]
Hello.

I'v installed your module and set driver of my device using Zadig but i'm getting an error.

TypeError: Cannot read property 'transfer' of undefined at USB.write

Any idea?

**Comment by GeorgiVachkov** [comment]
just as a debug hint you can check device.open(function(`error`) {... and if you get  same error as me - https://github.com/song940/node-escpos/issues/20 you can try changing USB.prototype.open so it does not set iface.setAltSetting, just call .claim() and the other stuff.
