### ISSUE TITLE
Can't require escpos into React component

### ISSUE THREAD

**Issue by xeb10154** [song940/node-escpos#215]
I am trying to require escpos package into a React Component `var escpos = require('escpos');`, but it keeps throwing an error where it says:

**TypeError: exists is not a function**
_Function.getRoot
node_modules/bindings/bindings.js:169_
```
  166 |   dir = process.cwd();
  167 | }
  168 | 
> 169 | if (exists(join(dir, 'package.json')) || exists(join(dir, 'node_modules'))) {
      | ^  170 |   // Found the 'package.json' file or 'node_modules' dir; we're done
  171 |   return dir;
  172 | }
```

I suspect it has something to do with Webpack. I ran the scripts individually in node and it works fine.

**Comment by Psychopoulet** [comment]
do you talk about react native, and not react ?
cause the package is obviously a node designed for one, and not not for front...

**Comment by song940** [comment]
https://github.com/song940/node-escpos/issues/197

**Comment by song940** [comment]
Duplicate of #197
