### ISSUE TITLE
Getting NotImplementedException on device.open()

### ISSUE THREAD

**Issue by minux84** [song940/node-escpos#22]
On mac os x sierra i get this error when I try to connect to a lan printer...what can I do?

**Comment by song940** [comment]
@minux84 which adapter do u use ?

**Comment by song940** [comment]
@minux84  node and npm versions ?

**Comment by minux84** [comment]
node 4.4.7 and npm 2.15.8 under MacOS X Sierra

**Comment by jor3l** [comment]
@minux84 try a newer node, works fine here with 6+ and 7+

**Comment by ArifADS** [comment]
@minux84 happend to me too with Node 4.x, updated to Node 6.x and not a problem now

**Comment by minux84** [comment]
upgradet to node 6.x and solved! thank you!
