### ISSUE TITLE
How to for loop and for each

### ISSUE THREAD

**Issue by artty58** [song940/node-escpos#224]
for loop and for each data to bill

**Comment by Psychopoulet** [comment]
that is not very explicit...
any case to submit ?

**Comment by artty58** [comment]
I want to print receipt in many items but it's not fixed then I think to use "for" or "foreach" for printing any item. Can you help me?

**Comment by artty58** [comment]
`for(var i; i<dataReceipt.length;i++){
                    .text("1. " + dataReceipt[i].tracking + " " + dataReceipt[i].province_name + " " + dataReceipt[i].zipcode)
                    .text('   ' + 'ชื่อผู้รับ : ' + dataReceipt[i].receiver_name)
                    .text('   ' + 'พัสดุธรรมดา ' + dataReceipt[i].alias_size + '/' + dataReceipt[i].parcel_type + "                " + dataReceipt[i].size_price + " บาท")
                    }`

**Comment by artty58** [comment]
![Capture](https://user-images.githubusercontent.com/35799888/64420982-b0d17900-d0ca-11e9-87d4-72c04355fddf.PNG)

**Comment by artty58** [comment]
![Capture2](https://user-images.githubusercontent.com/35799888/64421067-e9715280-d0ca-11e9-87e1-a7796065ebae.PNG)

**Comment by artty58** [comment]
@Psychopoulet @song940

**Comment by Psychopoulet** [comment]
... maybe because you try to use a function of an object without writing the object (".text()") ??
there is no issue with the package, only with the code ><
just read the debug stack...
