### ISSUE TITLE
adding console log response when cashdrawer is opened and closed.

### ISSUE THREAD

**Issue by Bhanuka94** [song940/node-escpos#225]
**Is it possible to add console log response when the cashdraw() function is triggered?** Need two different console log outputs when cash draw is opened and when cash draw is closed.
Is there a way to send a pulse when the cash drawer is getting closed?

![aaa](https://user-images.githubusercontent.com/51482638/64696662-9af1f880-d4bc-11e9-841a-3c25e3a9b53d.PNG)

**Comment by Psychopoulet** [comment]
I guess no, because there is no "detection" about it, only an electric impulsion for opening
