### ISSUE TITLE
可以支持并口调用吗

### ISSUE THREAD

**Issue by bigrocs** [song940/node-escpos#228]

**Comment by bigrocs** [comment]
好像没有并口驱动

**Comment by Psychopoulet** [comment]
in english, please ?

**Comment by bigrocs** [comment]
Does node-escpos support parallel port?

**Comment by Psychopoulet** [comment]
it can support any type of communication with the right adapter.
for example, the bluetooth one is recent, the module support this way of use since the bluetooth adapter exists
