### ISSUE TITLE
ESCPOS not working on Electron app

### ISSUE THREAD

**Issue by Bhanuka94** [song940/node-escpos#229]
![11](https://user-images.githubusercontent.com/51482638/65213962-cc268600-dac5-11e9-8dca-fa0495063e59.PNG)
![22](https://user-images.githubusercontent.com/51482638/65213963-ccbf1c80-dac5-11e9-8832-42f0a2600d6c.PNG)

The project built with Electron and ESCPOS library.

When clicking the "Print" button on electron window, the printer should print receipt and open cashdrawer.

But this is not happening.

When running "npm start"  the electron window(index.html) opens. The index.html print button brings only the alert window. But rest of the ESCPOS functions are not working.

When seperately running the "renderer.js" file in terminal by running "node renderer.js", the printer and cashdrawer works. The alert("Cash Drawer Open");  statement should be commented.

The problem is when clicking the print button in the window, only alert works. Other ESCPOS functions are not working.

****

Please note I have installed electron(latest version) with "npm install --save-dev electron" command. 
After that I added all "ESCPOS" library modules(https://github.com/song940/node-escpos) to a new folder called "escpos" inside node modules.  

My GitHub repo is given here. (https://github.com/Bhanuka94/electronCash).

**Comment by Psychopoulet** [comment]
did you try to install escpos dependencies ?
with a proper install of the module ("npm install escpos") instead of git download

**Comment by artty58** [comment]
![issue](https://user-images.githubusercontent.com/35799888/65297414-e168e680-db91-11e9-8344-a586681aa2a3.PNG)

**Comment by artty58** [comment]
yes , i do npm install escpos

**Comment by Bhanuka94** [comment]
> did you try to install escpos dependencies ?
> with a proper install of the module ("npm install escpos") instead of git download

Yes. I did install dependencies.
![33](https://user-images.githubusercontent.com/51482638/65297965-571b8500-db87-11e9-802b-357d1687f0fd.PNG)

**Comment by artty58** [comment]
I would like to download your project.

**Comment by artty58** [comment]
![escpos](https://user-images.githubusercontent.com/35799888/65298942-a1a4fd80-db97-11e9-8fe7-ff07571dd2b7.png)
How to

**Comment by artty58** [comment]
![lib](https://user-images.githubusercontent.com/35799888/65298995-e92b8980-db97-11e9-96ea-7c9950b53a83.PNG)

**Comment by Bhanuka94** [comment]
> I would like to download your project.

My GitHub repo is given here. (https://github.com/Bhanuka94/electronCash).

Once you open this with VS Code, install the following dependencies via terminal.
 
**npm install --save-dev electron

npm i escpos**

Afterwards, run the project "npm start".
/////////////////////////
Please note the system is not working well yet. I am still trying to open printer with window "print" button.

**Comment by Bhanuka94** [comment]
> did you try to install escpos dependencies ?
> with a proper install of the module ("npm install escpos") instead of git download

I tried some exception handling with try, catch statements to find the actual error. After clicking the print button, I got an error.

I got the error as "**Cannot access 'device' before initialization**'".

How to resolve this?
![55](https://user-images.githubusercontent.com/51482638/65299243-5e915d00-db8c-11e9-8afa-f66b8e955b99.PNG)

**Comment by Bhanuka94** [comment]
> > did you try to install escpos dependencies ?
> > with a proper install of the module ("npm install escpos") instead of git download
> 
> I tried some exception handling with try, catch statements to find the actual error. After clicking the print button, I got an error.
> 
> I got the error as "**Cannot access 'device' before initialization**'".
> 
> How to resolve this?
> ![55](https://user-images.githubusercontent.com/51482638/65299243-5e915d00-db8c-11e9-8afa-f66b8e955b99.PNG)

This is the code in renderer.js.
![66](https://user-images.githubusercontent.com/51482638/65299337-c3e54e00-db8c-11e9-9f4a-723ce1841f5f.PNG)

**Comment by Bhanuka94** [comment]
> ![escpos](https://user-images.githubusercontent.com/35799888/65298942-a1a4fd80-db97-11e9-8fe7-ff07571dd2b7.png)
> How to

You have to install the following dependencies via terminal.

npm install --save-dev electron
npm i escpos

**Comment by Psychopoulet** [comment]
why the f*ck is there two different conversations with two different people with two different projects ??

**Comment by Psychopoulet** [comment]
i will delete all the artty58's posts, who is certainly speaking of an other thread

**Comment by Psychopoulet** [comment]
you cannot use escpos in a client way. it's a server-side package which not works on browsers

**Comment by artty58** [comment]
ปากดีหรอไอสัส
