### ISSUE TITLE
Example integrated with HTML

### ISSUE THREAD

**Issue by mnengwa** [song940/node-escpos#233]
Thank you @song940 for this wonderful package. I've been able to run it via node on my terminal by following the provided examples. However upon integrating it to my web project(node_modules correctly) so that I can print from the browser, I just can't get it to work. Has there been anyone who has a working example that has the JS code embedded in Html?

**Comment by Psychopoulet** [comment]
this is not a front package, this is a node (server) one

**Comment by Psychopoulet** [comment]
you can create a micro-server with this, connected to a printer, and call it from your front
