### ISSUE TITLE
Examples/image.js not working

### ISSUE THREAD

**Issue by naphattharawat** [song940/node-escpos#236]
I clone source code from github and test print "examples/image.js" is not working

It error TypeError: printer.align(...).image(...).image is not a function
![Screen Shot 2562-11-13 at 01 21 38](https://user-images.githubusercontent.com/29243602/68698681-0b4bf180-05b4-11ea-841f-123373d003f5.png)

**Comment by DieserMerlin** [comment]
This is because the "image" function is asynchronous and returns a promise. So instead of
```javascript
printer.text("Hey").image(img).cut().close();
```
you need to do something similar to this:
```javascript
printer.text("Hey").image(img).then(() => printer.cut().close());

// Another example using an async-function:
const foo = async () => {
    (await printer.text("Hey").image(img)).cut().close();
};
```

You can also use raster instead of image which is synchronous and doesn't return a promise, but this way I cannot align the image very well.

```javascript
printer.raster(img).cut().close();
```

**Comment by 592da** [comment]
there is another issue.
I am using raster to print images, but in case the image is too big (byte length) the printer prints binary code... someone knows how to fix it?
