### ISSUE TITLE
中文字符无法使用 .size 方法控制大小吗？

### ISSUE THREAD

**Issue by tangsj** [song940/node-escpos#237]
printer.size(2.1, 2.1)
  .text('中文1')
  .size(1, 1)
  .text('中文2')

以上。「中文2」 还是会以  第1行设计的 2.1 大小进行打印
并且重新调用再也没有办法将中文大小设置回1， 只能重新启动打印机~~

**Comment by Psychopoulet** [comment]
in english, please ?

**Comment by darkfiredarkhalo** [comment]
连比亚迪都知道为中国汉字文化努力,我们做程序的却在这崇洋媚外,呵呵
