### ISSUE TITLE
Can someone recommend me a printer?

### ISSUE THREAD

**Issue by dolanmiu** [song940/node-escpos#238]
Which printers do you guys use for Linux and Windows?

Have you guys tried USB and Network printers? Which ones work?

**Comment by Psychopoulet** [comment]
I use this, it's my main (but in black)
https://www.epson.fr/viewcon/corporatesite/products/mainunits/overview/9450

**Comment by dolanmiu** [comment]
do you use this with Windows or Linux?

**Comment by Psychopoulet** [comment]
Both Linux and Windows.
Like said on the doc, you need a driver (Zadig) on Windows if you use it in a USB way.
You don't with web, serial or bluetooth.

**Comment by dolanmiu** [comment]
I am thinking of connecting the printer to ethernet (LAN)

and let a linux machine and a windows machine print from it

I don't need any drivers? Just this library?

**Comment by Psychopoulet** [comment]
yes, the network adapter manage the connection for you, you just have to set the right parameters (ip, etc...)
