### ISSUE TITLE
Convert EOS/POS back to text or image

### ISSUE THREAD

**Issue by zoell** [song940/node-escpos#239]
Hi,

I have a POS software that can use network printers (it is actually sending ESC/POS commands over TCP, nothing special) and I would like to create some kind of proxy to accept the commands and push it out to a normal printer. 

Would it be possible with node-escpos to convert the data back to some format that can be accepted by a standard printer which does not speak ESC/POS? Like simple text, image, or anything like that.

Thanks,
z

**Comment by Psychopoulet** [comment]
if you have already formatted your commands with ESC/POS standards, you don't need node-escpos.
this package encode data and send them to printers, but it does not decode them
