### ISSUE TITLE
Npm install time error occured

### ISSUE THREAD

**Issue by sohel-navsoft1** [song940/node-escpos#240]
> node-bluetooth@1.2.6 install /home/nav45/Desktop/project/ex/irsfrontend/node_modules/node-bluetooth
> node-gyp configure build

make: Entering directory '/home/nav45/Desktop/project/ex/irsfrontend/node_modules/node-bluetooth/build'
  CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o
../src/linux/BluetoothSerialPort.cc:18:14: error: variable or field ‘InitAll’ declared void
 void InitAll(Handle<Object> exports) {
              ^
../src/linux/BluetoothSerialPort.cc:18:14: error: ‘Handle’ was not declared in this scope
../src/linux/BluetoothSerialPort.cc:18:27: error: expected primary-expression before ‘>’ token
 void InitAll(Handle<Object> exports) {
                           ^
../src/linux/BluetoothSerialPort.cc:18:29: error: ‘exports’ was not declared in this scope
 void InitAll(Handle<Object> exports) {
                             ^
In file included from ../src/linux/BluetoothSerialPort.cc:12:0:
../src/linux/BluetoothSerialPort.cc:23:34: error: ‘InitAll’ was not declared in this scope
 NODE_MODULE(BluetoothSerialPort, InitAll)
                                  ^
/home/nav45/.cache/node-gyp/12.13.1/include/node/node.h:566:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^
../src/linux/BluetoothSerialPort.cc:23:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(BluetoothSerialPort, InitAll)
node version 12.13.1
npm version 6.12.1

**Comment by bigrocs** [comment]
同样的问题求解
