### ISSUE TITLE
Error when printer is offline! ip network

### ISSUE THREAD

**Issue by midiat** [song940/node-escpos#252]
The application crash if the printer is offline using ip network connection, Im trying to catch and throw error when the ip is not found, but I can't make it work and the app keep crashing after looking for ip of disconnected printer.
If there is any way to continue the application without error after not finding the printer.
any help will be appreciated.

**Comment by violetzie** [comment]
Seems like the network open() has a callback with the possible error parameter being returned. So a 

`open( (err) => { /* do something with error if it exists*/ });`

 should be enough, dealt with a similar problem via the USB adapter. The readme does not specify the error param of the callback function but after looking at the source, it is there. No try/catch block needed and in fact will not probably work I believe.
