### ISSUE TITLE
Should I replace existing driver ?

### ISSUE THREAD

**Issue by imMayankRaj** [song940/node-escpos#253]
I have an epson printer pre-configured with a driver. So should I replace it with WIN-USB driver using zadig? Is it necessary to use WIN-USB as the driver or the driver provided along with the printer will also work ?

**Comment by Psychopoulet** [comment]
depends of your connection to the printer. drivers are useless when you connect it with network or serial, for example

**Comment by imMayankRaj** [comment]
I am only asking for the USB printer. I had a printer pre-configured with a driver I tried printing but it was giving LIBUSB_ERROR_NOT_SUPPORTED error but upon installing WIN-USB driver it worked.

**Comment by Psychopoulet** [comment]
so, the answer is yes ^^
