### ISSUE TITLE
Font B width issue

### ISSUE THREAD

**Issue by azjol** [song940/node-escpos#255]
Hello,
I set option `width:64` while creating Printer instance. But if I change font to `font B`, width is set to 56.

```
self.printer = new escpos.Printer(self.device, {width:64} );
self.printer.font('b');
```

**Comment by violetzie** [comment]
Sorry about the commit reference mess, had a typo and having a massive overwork stroke. Anyway, here's a possible proposed fix for this issue => #257 ?
