### ISSUE TITLE
escpos@v3

### ISSUE THREAD

**Issue by lsongdev** [song940/node-escpos#264]
Hello everyone, 

Today, we published first alpha version of v3. A BREAKING CHANGE.

I move adapter out of escpos the main package to `escpos-*` package to fix #221 #260 #214 

Welcome report bug, or fork + commit and send pull-request to this repo. I'll review and merge it ASAP.

Thanks.

**Comment by gersur** [comment]
Why the version back to 0.x.x?
This can led confusing for package manager
If it breaking changes, then do major versioning.

Please follow semantic versioning
https://devhints.io/semver
-----EDIT-------
It's an alpha version
Should be v3.0.0-alpha-1

**Comment by bigrocs** [comment]
Is there a tutorial for using v3

**Comment by bigrocs** [comment]
v3
Cannot find module './printer'
Printer.Printer = require('./printer');

![image](https://user-images.githubusercontent.com/15796287/75205357-870e2a80-57ae-11ea-825c-73efc1dbc9a4.png)

**Comment by lsongdev** [comment]
@g3rrydanc3 Oh, my mistake, [now it's correct](https://github.com/song940/node-escpos/commit/a3a65c61c0b990298258331f54546a93d6875ddb).
@bigrocs I updated [README file](https://github.com/song940/node-escpos#example). And it will show you how to use in v3 version.

**Comment by chourouk-mrad** [comment]
@song940 

When i try to connect to the printer via network. 

`const connection = new escpos.Network(address);`

I get the error **Unhandled Rejection (TypeError): net.Socket is not a constructor**

Do you have an idea if it's related to the new released version or it's something else ?

_NB: my printer is EPSON TM-U220_

**Comment by gpallas16** [comment]
When I run npm i escpos-bluetooth runs automatically node-gyp configure build and then I get this error:

ELIFECYCLE
npm ERR! errno 1
npm ERR! node-bluetooth@1.2.6 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-bluetooth@1.2.6 install script.

Should I install or configure anything else before installing the bluetooth adapter?

My current setup:
   Windows 10
   Electron 7.1.5
   Node 12.16.1
   Npm 6.13.4

**Comment by bigrocs** [comment]
@gpallas16  I encountered a problem while building node-bluetooth

**Comment by lsongdev** [comment]
@gpallas16 Please referred to [node-bluetooth](https://github.com/song940/node-bluetooth) .

**Comment by lsongdev** [comment]
@chourouk-mrad what version of Node.js ?

**Comment by sudippaudel793** [comment]
> @gpallas16 Please referred to [node-bluetooth](https://github.com/song940/node-bluetooth) .

same problem occured with mac os. i have node-gyp of version v6.1.0 but also escpos-bluetooth is not installed and shows the error below:-
![image](https://user-images.githubusercontent.com/61705577/78653791-5c51de80-78e3-11ea-8c8d-1535745da642.png)

**Comment by yelhouti** [comment]
Since we are moving to v3 and already have breaking changes, can we just use async await instead of all the callbacks.
For example open could just return a Promise that fails when open fails...

**Comment by ehmad** [comment]
> @song940
> 
> 当我尝试通过网络连接到打印机时。
> 
> `const connection = new escpos.Network(address);`
> 
> 我收到错误**Unhandled Rejection (TypeError): net.Socket is not a constructor**
> 
> 你知道它是否与新发布的版本有关还是其他什么？
> 
> _注意：我的打印机是 EPSON TM-U220_

I also encountered the same problem. Did you solve it?

**Comment by ehmad** [comment]
> @chourouk-mrad什么版本的 Node.js？

I also encountered the same problem.
node:14.17.0

**Comment by ehmad** [comment]
> @ chourouk-mrad
> 
> When i try to connect to the printer via network.
> 
> `const connection = new escpos.Network(address);`
> 
> I get the error **Unhandled Rejection (TypeError): net.Socket is not a constructor**
> 
> Do you have an idea if it's related to the new released version or it's something else ?
> 
> _NB: my printer is EPSON TM-U220_

I also encountered the same problem.Did you solve it?

**Comment by FawzyMokhtar** [comment]
Can we use this package in Ionic 6 to support printing on Android & IOS ? @song940

**Comment by prashanta-sam-velectico** [comment]
> > @ chourouk-mrad
> > When i try to connect to the printer via network.
> > `const connection = new escpos.Network(address);`
> > I get the error **Unhandled Rejection (TypeError): net.Socket is not a constructor**
> > Do you have an idea if it's related to the new released version or it's something else ?
> > _NB: my printer is EPSON TM-U220_
> 
> I also encountered the same problem.Did you solve it?

>> I am getting  this error  "escpos.Network is not a constructor"

**Comment by prashanta-sam-velectico** [comment]
I am getting this error "escpos.Network is not a constructor"
