### ISSUE TITLE
Can't resolve 'escpos-bluetooth'

### ISSUE THREAD

**Issue by sudippaudel793** [song940/node-escpos#272]
what to do with this???

**Comment by lsongdev** [comment]
https://www.npmjs.com/package/escpos-bluetooth

**Comment by sudippaudel793** [comment]
<img width="859" alt="Screen Shot 2020-03-15 at 21 05 54" src="https://user-images.githubusercontent.com/61705577/76704411-ed78cf80-6700-11ea-9254-6812000cb46e.png">
This issues dont let me move forward, while running command npm i escpos-bluetooth

**Comment by paul122297** [comment]
Same issue here using Ubuntu and Electron Vue

**Comment by marquipaul** [comment]
Same issue here using Electron and Vue

`
![Screenshot from 2020-04-22 02-01-59](https://user-images.githubusercontent.com/28916689/79898171-5f99ae00-843d-11ea-97d1-e55aed7957ac.png)
![Screenshot from 2020-04-22 02-02-13](https://user-images.githubusercontent.com/28916689/79898183-66c0bc00-843d-11ea-890e-e9c90229e5e7.png)

`

**Comment by boustanihani** [comment]
Having same issue..
