### ISSUE TITLE
The parameters of function  tableCustom are inconsistent with those in the document.

### ISSUE THREAD

**Issue by SantiagoFan** [song940/node-escpos#275]
code is    tableCustom = function (data, encoding, size) 
doc  is tableCustom(data,{encodoing ,size})

**Comment by SinanMtl** [comment]
@SantiagoFan This improvements have not been published on npm, yet. @song940 Could you publish last changes as v3.0.0-alpha.3 on npm if its ok?

**Comment by lsongdev** [comment]
> @SantiagoFan This improvements have not been published on npm, yet. @song940 Could you publish last changes as v3.0.0-alpha.3 on npm if its ok?

Sure! v3.0.0-alpha.3 published.

**Comment by SantiagoFan** [comment]
thinks for the quick response
