### ISSUE TITLE
only buffer output

### ISSUE THREAD

**Issue by gurselk** [song940/node-escpos#276]
How can I get the buffer version of "esc pos" commands in this package?

I will use typescript

**Comment by gurselk** [comment]
I will use typescript

**Comment by Psychopoulet** [comment]
by using the "command line" adapter ? or with the official EPSON documentation

**Comment by gurselk** [comment]
%100 javascript buffer please

**Comment by lsongdev** [comment]
@gurselk use [escpos-console](https://github.com/song940/node-escpos/blob/v3/packages/console/index.js) adapter.
