### ISSUE TITLE
only number problem

### ISSUE THREAD

**Issue by gurselk** [song940/node-escpos#278]
what is problem ?
![IMG_3340](https://user-images.githubusercontent.com/2247868/78895294-3c532400-7a77-11ea-9c0f-8a356973c7ee.JPG)

iconv-lite alternative new TextDecoder() problem help me

**Comment by Psychopoulet** [comment]
OS ? node version ? package version ? etc...

**Comment by gurselk** [comment]
i am trying to make the package work in browser i need to find an alternative that iconv-lite is not working

**Comment by Psychopoulet** [comment]
as said in the first sentence of the documentation, it's not a browser package, it is only for node...
