### ISSUE TITLE
BASE64 image data url support?

### ISSUE THREAD

**Issue by ray-man** [song940/node-escpos#28]
I am trying to use base64 image data url but am getting error
`TypeError: url.indexOf is not a function`

Is there any way around or am doing something wrong here?

```js
let device = new Escpos.USB();
let printer = new Escpos.Printer(device);
Escpos.Image.load(dataUrl, function(image) {
  device.open(function() {
  printer
  .align('ct')
  .raster(image)
  .cut()
  .close();
  });
});
```

**Comment by song940** [comment]
`url` is the path to the file. It can be a relative path, an http url, a data url, or an in-memory Buffer.
`TypeError: url.indexOf is not a function` means your url is not a `string` . Is your `url` correct?

**Comment by rehmanShafi** [comment]
i am using Data Url `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAaoAAAJFCAYAAACMdbM8AAAg.......`

**Comment by rehmanShafi** [comment]
Solved it, data passed to `Escpos.Image.load` wasn't in perfect shape, a little bit cleaning got the job done.
Thanks for response.

**Comment by vinothmoorthkumar** [comment]
How did you fixed this ??

**Comment by Psychopoulet** [comment]
"data passed to Escpos.Image.load wasn't in perfect shape, a little bit cleaning got the job done"

**Comment by ray-man** [comment]
The problem is back, Here are details, I am using BASE64 image data, 
`Escpos.Image.load(data.image,function(image) {
        device.open(function() {
          printer
            .align('ct')
            .image(image)
            .cut()
            .close();
        });
      });`
That's how my code look's like , result with `.image(image)` is as below
https://ibb.co/kUvsrz

Any suggestions ?
