### ISSUE TITLE
Create receipt dynamic for gastronomy

### ISSUE THREAD

**Issue by ferhattelci** [song940/node-escpos#298]
Hello :) 
I'm trying to create a layout for our restaurant, but unfortunately I'm not really getting anywhere. 

I would like to have the headline in the middle with the size (1,1) and in bold. That worked out without any problems 

Only everything that comes after it should be smaller, but the style of the headline will still be used. 

Can you tell me what I'm doing wrong? Or show an example? The data is intercepted by the API. 

This is my example:

`const escpos = require('escpos');
escpos.USB = require('escpos-usb');

const device  = new escpos.USB(0x0416, 0x5011);
const printer = new escpos.Printer(device);

const printHeader = (text) => {
  device.open(function () {
    printer
      .font('A')
      .align('CT')
      .style('bu')
      .size(1, 1)
      .text(text)
      .close();
  });
}

const printDetails = () => {
  device.open(function () {
    printer
      .font('B')
      .align('LT')
      .size(2, 1)
      .text("Kellner: XY")
      .text("2020-06-27 15:12 Uhr")
      .close();
  });
}

function printItems(items){
  device.open(function(){
    printer.font('a')
      .size(2,1);
    items.forEach(function(item) {
      printer.size(3,1)
        .print(item["amount"] + "X ")
        .println(item["name"]);
    });
  });
}

var items = [
  {"name": "ABC",
    "amount" : 2},
  {"name": "DEF",
    "amount" : 1}
];

printHeader("Tisch 3");
printDetails();`
printItems(items);

My Layout should look like this [
![layout](https://user-images.githubusercontent.com/33453952/85948488-7be02c80-b951-11ea-96b3-23223f8bde65.png)
](url)

**Comment by Psychopoulet** [comment]
1) you must respect asynchronous works, and wait for previous print ending ("printHeader") before run next one ("printDetails")
2) you should not open and close device for each operation, but before and after each ticket
3) you should manage asynchronous close ending

function printAll ((device, printer, text, items, cb) => {

	device.open(() => {

		// header

		printer
			.font("A")
			.align("CT")
			.style("bu")
			.size(1, 1)
			.text(text);

		// details

		printer
			.font("B")
			.align("LT")
			.size(2, 1)
			.text("Kellner: XY")
			.text("2020-06-27 15:12 Uhr");

		// items

		printer
			.font("a")
			.size(3,1);

		items.forEach((item) => {

			printer
				.print(item["amount"] + "X ")
				.println(item["name"]);

		});

		printer.close(cb);

	});

}
