### ISSUE TITLE
Image support?

### ISSUE THREAD

**Issue by zxlin** [song940/node-escpos#3]
Hi, first of all, great module, it's a very impressive project to port all the escpos functionalities to JS.

I was wondering if you had any plans to add image printing support? I currently spawn a python script to do the image processing part, but that's not entirely a native solution.

**Comment by cuplizian** [comment]
I think you miss this?
https://github.com/song940/node-escpos#imageimage_nameext

**Comment by jor3l** [comment]
@cuplizian that doesn't work. It does print a QR code (I was able to get that working) but the code does not read any image and then prints it.

**Comment by zxlin** [comment]
@cuplizian Yea, I think that's just @song940 starting to explore image support.

**Comment by song940** [comment]
Not support yet, but I'm working on it .

**Comment by song940** [comment]
@all yes

**Comment by zxlin** [comment]
Awesome! Thanks for this!
