### ISSUE TITLE
German Encoding

### ISSUE THREAD

**Issue by mats-codes** [song940/node-escpos#302]
Hey,

first of all thanks for the awesome project! Since I'm from germany I'd need letter like ä, ö, ü, ß, &. Is there any documented overview of possible encodingd?

Does anybody know, which I can pick?

Thanks and Regards

**Comment by mats-codes** [comment]
Found the solution:
{
  encoding: 'Cp850',
}

**Comment by oliverdotbecker** [comment]
Correct. For umlauts just add:

`.encode('Cp850');`

**Comment by ngmiduc** [comment]
Hi!
Somehow I have added "cp850" or "Cp850" and the ä, ö, ü ... are still malformatted.

I init encoding with 

`const printer = new escpos.Printer(device, { encoding: 'Cp850' })`

I use

`escpos` version 3.0.0-alpha.6
`escpos-usb` version 3.0.0-alpha.4
`node` version 14.15.1
