### ISSUE TITLE
escpos-screen package ./command.js module not found

### ISSUE THREAD

**Issue by conquera99** [song940/node-escpos#305]
hi,

after install the escpos-screen package, then this error show. its not included in the package.
```Error: Cannot find module './commands'```
```Error: Cannot find module './promiseify'```
is that module is same with core escpos ```commands.js```?

the ```promiseify``` is not found in the core escpos or it is same with ```promisify.js```?

install:
npm install escpos-screen

the core escpos package was installed before

thank you for your awesome project

**Comment by lsongdev** [comment]
escpos-screen@3.0.0-alpha.6

**Comment by conquera99** [comment]
thank you!
