### ISSUE TITLE
Barcodes are not printed (only works with EAN8) 

### ISSUE THREAD

**Issue by kbw3** [song940/node-escpos#31]
Hi, I'm having problems when printing barcodes. I just changed the barcode type on the example code, but no luck. My printer is an EPSON TM-T20II and according to the documentation it supports all the barcode formats available in your code. I hope you can help me find out what's happening. 

```js
device.open(function(){
  printer
  .font('a')
  .align('ct')
  .style('bu')
  .size(1, 1)
  .text('The quick brown fox jumps over the lazy dog')
  .barcode('B012ABCDabcd','CODE128')
  .cut()
});
```

**Comment by song940** [comment]
May your printer does not support this directive, use [printer#image](https://github.com/song940/node-escpos/blob/master/examples/image.js) instead of it.
