### ISSUE TITLE
Printer Not Found Using EPSON TM-U220

### ISSUE THREAD

**Issue by bobyharmoko** [song940/node-escpos#322]
Hi i got some issue when using printer EPSON TM-U220 , When i using that device the library got error and says that the printer is not found,

I already install the printer driver and using zadig too, but still got error printer is not found, Any sollution for this problem?

**Comment by bobyharmoko** [comment]
Already Solved

**Comment by conquera99** [comment]
Hi, can you share your solutions to this issue? Thank you

**Comment by AndhikaR** [comment]
hey can you share what are you doing? mine doesnt works too

**Comment by conquera99** [comment]
switched to [node-printer](https://www.npmjs.com/package/@thiagoelg/node-printer) and [node-thermal-printer](https://www.npmjs.com/package/@thiagoelg/node-printer)
