### ISSUE TITLE
TypeError: Cannot read property of 'indexOf'... trying to connect to SerialPort Fiscal Printer

### ISSUE THREAD

**Issue by juanzeta33** [song940/node-escpos#325]
Hi guys, 

I dont know if this is an issue of the lib or a missconfig mine, but I'm geting this error when I try to connect to SerialPort printer (currently in emulation) because is a Fiscal Printer (Bussines things in my country).

I'm using COM4 serial port and using this lines as indicates @song940 in this [url ](https://github.com/song940/node-escpos/blob/v3/packages/serialport/README.md)
```
const escpos = require('escpos');
escpos.SerialPort = require('escpos-serialport');

const serialDeviceOnWindows = new escpos.SerialPort('COM10');
const serialDeviceOnLinux = new escpos.SerialPort('/dev/usb/lp0', {
  baudRate: 14400,
  stopBit: 2
});
```

I was happy because is so simple when I connect with networks printer, but I see for SerialPorts printers is another things.

Can you tell is I have something wrong? Tell if I need to provide more code.

My setup is Vue.js with Electron JS to run the printer.
```
"escpos": "^3.0.0-alpha.6",
"escpos-network": "^3.0.0-alpha.5",
"escpos-serialport": "^3.0.0-alpha.4",
```

Image of the error
![image](https://user-images.githubusercontent.com/36899684/102296429-52c15180-3f1b-11eb-8703-10fa726b459c.png)

**Comment by Scott1995** [comment]
How did you solve the problem

**Comment by juanzeta33** [comment]
@Scott1995 I'm still working and figthing with them!
