### ISSUE TITLE
Linux common workflow

### ISSUE THREAD

**Issue by oliverdotbecker** [song940/node-escpos#335]
Hello,

I'm using a HOIN HOP-E802 Printer. For linux they are providing no USB driver. Only a driver working with CUPS. Is there a way to send the ESC commands over CUPS to such a generic printer, or does somebody have a source to a genreric  80mm USB printer dirver for linux.

I have it working with the given USB driver for Windows. But can't get it going on a Raspberry PI 3 (raspbian).

Ideas?

**Comment by oliverdotbecker** [comment]
Never mind.

**Comment by ihsankl** [comment]
did you make it? mine isn't working at all

**Comment by oliverdotbecker** [comment]
Here is mý documentation how I got it work. It's a year ago that I've wrote this, and currently I'm out of time to double check. Hope this helps you.
[How to install driver.md](https://github.com/song940/node-escpos/files/8027857/How.to.install.driver.md)
Note: Some decribed buttons in the WebGUI are German.
