### ISSUE TITLE
USB Adapter, cannot close / disconnecting adapter

### ISSUE THREAD

**Issue by adenvt** [song940/node-escpos#35]
My `index.js`
```js
const escpos = require('escpos');

const device  = new escpos.USB();
const printer = new escpos.Printer(device);

device.open(() => {
  printer
    .text('Hello World')
    .feed()
    .cut()
    .close(() => {
      console.log('Close')
    })
});
```
I run via terminal
```bash
node index.js
```
Everything is OK... just script not stop, need to press <kbd>Ctrl + c</kbd> to stop it,
and close's callback never called.

I try change using Serial. work properly.

Note:
- OS: Ubuntu 16.04
- Node: 6.10.2

**Comment by song940** [comment]
When u press <kbd>Ctrl + C</kbd>, terminal will send `SIGINT` to our program .
i guess `SerialPort` listen this signal and close the port on program exit, but usb does not do it.

so, we can add this code to our program ... 
```js
process.on('SIGINT', () =>   printer.close());

**Comment by nadbm** [comment]
@song940  I think you understood the problem wrong. It is not that CTRL+C doesn't stop the code, but he is FORCED to kill the application. I will submit a PR to fix this shortly.
