### ISSUE TITLE
How can I change the size of the text?

### ISSUE THREAD

**Issue by BryanJ-97** [song940/node-escpos#350]
Hello everyone, I don't know how can i change the size of the text with your library :(,  your library is so cool, but i have problems with the size of the text, this is my code
 .font('A')
      .align('CT')
      .style('BU')
      .size(1, 1)
      .text('---------------------')
      .text("Cafeteria Restaurante" )
      .text('---------------------')
      .align('LT')
      .text("Factura N: 123 \t")
      .text("Fecha: 03/02/2021\n")
      .text("Cliente: Bryan Alban\t")
      .text("Atendido por: APAREDES\n")
      .text('---------------------')
      .table(["Descripcion","Cantidad","Valor"])
      .text('----------- ------ ---')
      .table(["Agua","1","0.50"])
      .text("----------------------")
      .feed(1)
      .align('RT')
      .text('Total: 0.50')
      .align('CT')
      .text("Gracias por preferirnos")
      .feed(1)

and when I excecute that code I get this, the letters is so big :c,
Maybe you can help me with this
![WhatsApp Image 2021-04-15 at 1 01 44 AM](https://user-images.githubusercontent.com/53631163/114821445-32e55180-9d86-11eb-8ef0-5ee881fa9be4.jpeg)

the printer I'm using is a Logic Controls LR2000:
https://logiccontrols.com/products/hardware/peripherals/printers/lr2000/

**Comment by andrefmandrade** [comment]
Check this issue #345
