### ISSUE TITLE
escpos.Serial is not a constructor

### ISSUE THREAD

**Issue by rareh21** [song940/node-escpos#356]
Hi,
I am trying to connect using serial, but it shows escpos.Serial is not a constructor. How to fix this issue. Please suggest me a way to solve this. Thanks

**Comment by pilz97** [comment]
I have the same issue

**Comment by ehmad** [comment]
I have the same issue

**Comment by johnstan** [comment]
I have the same issue

**Comment by lsongdev** [comment]
https://github.com/song940/node-escpos/blob/v3/packages/serialport/README.md

**Comment by johnstan** [comment]
Ah nice, thanks! Assume after changing the serialPort part, escpos.Screen etc. goes as per the normal docs?

**Comment by johnstan** [comment]
Hmm, no - now escpos.Screen is not a constructor. This used to work fine, but now all of the screen commands in the examples seem to be broken

**Comment by johnstan** [comment]
Ok, got it - similar trick for the screen as for the serial. 

```npm i escpos-screen``` and then
```escpos.Screen = require('escpos-screen')```

Leaving this here for anyone who searches in the future

**Comment by ma-zal** [comment]
If you are using `escpos` version 2, there is an issue with new major release of library `serialport` (version 10 with breaking changes has been released).

See my https://github.com/song940/node-escpos/issues/383#issuecomment-1094356051
