### ISSUE TITLE
Adapters for chrome USB and Bluetooth?

### ISSUE THREAD

**Issue by jor3l** [song940/node-escpos#363]
Hi @song940, I have a working version with both chrome USB and native bluetooth support, the thing is, this repo contains libs that only work for node not the browser, should we work on moving those libraries to the adapter package so we can have a more global escpos code not limited to node only?. Let me know what you think.

Web + React Native + Ionic and others = Adapters

**Comment by jor3l** [comment]
Never mind, this seems to be already implemented! I'm going to work on those adapters and submit a pull request!

**Comment by kamilml** [comment]
> Never mind, this seems to be already implemented! I'm going to work on those adapters and submit a pull request!

Suena genial!

I want to use it on react/web :)
