### ISSUE TITLE
Example not working - truncated image qrcode

### ISSUE THREAD

**Issue by vekexasia** [song940/node-escpos#37]
Hello,

thank you for the project.

I've tried the following snippet with both USB and Serial device connection
![image](https://cloud.githubusercontent.com/assets/200523/25057470/701e43ae-2170-11e7-99a8-c701bdd4f1a3.png)

the result is a truncated qrcode. (Every time at the same spot) .... I'm not sure if that's a bug in raster process or just a communication issue somewhere.
![image](https://cloud.githubusercontent.com/assets/200523/25057507/dcd74c84-2170-11e7-88a6-c4d62ad3749f.png)

**Comment by vekexasia** [comment]
After further investication:

Assuming that: the problem does not reside on my printer (which i don't think since other apps could print images just fine);

The problem might be in `image.js`.`toRaster()` i see width is getting "/8" but height is not. While the code is obscure to me it looked strange that just one dimension was going to be shrinked in the process.

I also saw that GS_V0 command is marked as obsolete and EPSON recommends using GS L (112 &50) to perform the same task. their documentation is too hard for me since I got in touch with esc pos standard just few hours back and I lack the needed knowledge to fully comprehend those parameters.

**Comment by jor3l** [comment]
What about printing an QR code image? Does it get truncated too?

**Comment by vekexasia** [comment]
With .Image?

Il 15 apr 2017 01:01, "Jose Vera" <notifications@github.com> ha scritto:

**Comment by vekexasia** [comment]
I used your image example with the following code and tux.png:
![image](https://cloud.githubusercontent.com/assets/200523/25062494/5ce420da-21cd-11e7-8bac-071cfa35f4e3.png)

The result is the following:

![image](https://cloud.githubusercontent.com/assets/200523/25062505/835dc270-21cd-11e7-934d-989b837432cd.png)

Do images need to have a maximum size to be printed ? I tried with a "large" jpg but i got only black patterns printed.

**Comment by uyu423** [comment]
I can not print the qr code normally either. I think there is a slight difference in specifications between printer manufacturers. In my case, the hardware does not seem to have a value defined for the qr code output. (I use an A7 printer) I think it is necessary to discuss how to solve the problem when specifications vary from manufacturer to manufacturer.

**Comment by song940** [comment]
@vekexasia you can contact your printer's manufacturer, any questions u can reopen this issues .
