### ISSUE TITLE
Multiple rows in custom table

### ISSUE THREAD

**Issue by sKY02644** [song940/node-escpos#377]
Please how do i print multiple rows for the tableCustom function

**Comment by sKY02644** [comment]
solved

**Comment by khanof89** [comment]
@sKY02644  how did you solve it ?

**Comment by sKY02644** [comment]
![code](https://user-images.githubusercontent.com/25549285/155997362-5522677f-a6a3-455a-b43a-1c49984fd0c6.png)

**Comment by khanof89** [comment]
Thank you so much, this repository is so dead the maintainer is not replying to any tickets for a long time. But your code helps

**Comment by sKY02644** [comment]
Happy it helped you
