### ISSUE TITLE
sorry but i can´t do that

### ISSUE THREAD

**Issue by netico14** [song940/node-escpos#38]
I'm sorry it's my fault, I'm new to this, I ran the zadig program, select the printer, wait for it to finish and close the program, run the server.js and tell me that it can not find the printer, look for this problem but without success , Any idea of my error, thank you very much.

**Comment by jor3l** [comment]
Share your code

**Comment by netico14** [comment]
Hello jor3l, my code:
`const escpos = require('escpos');

const device  = new escpos.USB();
const printer = new escpos.Printer(device);

device.open(() => {
  printer
    .text('Hello World')
    .feed()
    .cut()
    .close(() => {
      console.log('Close')
    })
});`
and the error:
[url=http://subefotos.com/ver/?98ede98456f00ea35a9b2bda664ffc9bo.jpg][img]http://thumbs.subefotos.com/98ede98456f00ea35a9b2bda664ffc9bo.jpg[/img][/url]

thanks

**Comment by netico14** [comment]
![error_escpos](https://cloud.githubusercontent.com/assets/26560659/25066584/86ef894c-21ef-11e7-803e-0c2f8a09d3f7.JPG)

**Comment by jor3l** [comment]
Seems to me that your PC is not configured well, are you able to print using another software?

**Comment by netico14** [comment]
Thanks you, yes sir, i'm try from notepad

**Comment by netico14** [comment]
Thanks, i can print now, between usb() need put the VendorID and ProductID, example usb(0x2B5, 0x204)
