### ISSUE TITLE
Can not find printer at new USB

### ISSUE THREAD

**Issue by AndhikaR** [song940/node-escpos#387]
running on windows, i already installed the printer driver and zadig, implemented on electron, any idea what cause this?

**Comment by YovanggaAnandhika** [comment]
You must replacing Driver with Zadig, select Your Printer Name and Replace Driver(WinUSB).

and run electron-rebuild -f -w escpos-usb for prebuild electron

**Comment by YovanggaAnandhika** [comment]
Please Upload To NPM new Pull Request @jor3l
