### ISSUE TITLE
Thermal Printer Dascom DT-230 don't work (Linux)

### ISSUE THREAD

**Issue by Kaplas85** [song940/node-escpos#413]
Hi! I'm trying to work with a Thermal Printer Dascom DT-230 in Linux.

Trying to use with serial port because the port that the printer use is the /dev/ttyACM0 but with any config or packages don't work.

Someone work some with that printer or can help me?

**Comment by dohooo** [comment]
#412

**Comment by dohooo** [comment]
At [here](https://github.com/node-escpos/driver/issues/13#issue-1424097285).
