### ISSUE TITLE
Can we send an HTML or PDF file to print?

### ISSUE THREAD

**Issue by burakkilic** [song940/node-escpos#45]
Hello,

We need to print aligned rich text for restaurant receipts.

![image](https://cloud.githubusercontent.com/assets/123382/25749876/9c1a8a0a-31b8-11e7-8ae6-8d76ee88b56b.png)

What is the best way to to that?

**Comment by Psychopoulet** [comment]
add some spaces. I created a wrapper for a project XML > ESCPOS which automaticly add some spaces to the ticket for that, you can do the same...

**Comment by conquera99** [comment]
hi, do you have an example for this?

currently the print output is not consistent in different printer
or to make it consistent, do i need to convert to image or pdf?
actually i need to change the font family too 

thank you

**Comment by conquera99** [comment]
> hi, do you have an example for this?
> 
> currently the print output is not consistent in different printer
> 
> thank you

or did you mean to send XML to `.text()` method?
