### ISSUE TITLE
Printing for network using smb can't function

### ISSUE THREAD

**Issue by AlexandreSousa** [song940/node-escpos#46]
Hello everyone, how do I print to a shared printer I tried using the following command var device = new escpos.Network ('smb: //192.168.10.241/TM-T20'); But it did not work

**Comment by song940** [comment]
does not support smb protocol yet

**Comment by AlexandreSousa** [comment]
Is it possible to print over the network?

**Comment by song940** [comment]
`node-escpos` can print via network, but now only support raw protocol .

**Comment by AlexandreSousa** [comment]
And how to print using the raw protocol

**Comment by song940** [comment]
Just like the serial protocol, the protocol is transmitted to the printer through the network without being encapsulated by SMB or CUP .
