### ISSUE TITLE
How to align text to the left and right in one line?

### ISSUE THREAD

**Issue by toure20** [song940/node-escpos#52]
Could you describe how to align text to the left and right in one line?
Thank you!
<img width="329" alt="2017-07-04 16 45 19" src="https://user-images.githubusercontent.com/15181919/27827251-33e64196-60d8-11e7-9969-05bf28f4cccc.png">

**Comment by song940** [comment]
You can align left, then print, and then align right print right .

like this: 

```js
printer
.align('left')
.print('SM Water')
.align('right')
.print('0.00')
.flush();
```

**Comment by toure20** [comment]
Thank you for reply! I tried by that way, but after setting second align, text prints at new line. Is it depends on pos-printer type?

**Comment by toure20** [comment]
Thanks for your quick reply:) I tried by that way, but text (i mean 0.00) after new alignment printed in new line. May be it depends on what kind of pos-printer i have?
<img width="733" alt="2017-07-04 22 37 49" src="https://user-images.githubusercontent.com/15181919/27837977-7e4f7258-6109-11e7-8839-98e3c35e7ffe.png">

**Comment by Psychopoulet** [comment]
you can pad it with spaces
