### ISSUE TITLE
Is this printer compatible with node-escpos?

### ISSUE THREAD

**Issue by emrealparslan93** [song940/node-escpos#53]
Hello, 
I'm using Mac and I'm trying to use this printer https://epson.com/For-Work/Point-of-Sale/POS-Printers/TM-T88V-POS-Receipt-Printer/p/C31CA85084 with this library. But it doesn't see the printer although I installed the driver of it. Is it possible that this printer does not support ESC/POS commands? Thanks.

**Comment by Hayvanimal** [comment]
Probably that printer supports ESC/POS commands, but '**node-escpos**' is using '**libusb**' library...
Btw '**node-escpos**' has no reletion to specific printer drivers i think..

Try this..

`brew install libusb-compat `

İyi Çalışmalar..

**Comment by Psychopoulet** [comment]
escpos modules (node, python, php, etc...) are essentialy based on the EPSON standards, which are used by 80% of the printers. It can append that a specific printer does only what it want, but with an EPSON it should work well.

**Comment by emrealparslan93** [comment]
@Hayvanimal @Psychopoulet Thank you both for your answers. The issue was completely different. Sorry for inconvenience.
