### ISSUE TITLE
Error: Can not find printer

### ISSUE THREAD

**Issue by sadlyblue** [song940/node-escpos#6]
Hi,
I'm trying to print from node.js to a Epson Tm-T70II thermal printer connect with an usb cable.
I get the error "Error: Can not find printer" when trying the index.js. The printer is working. Even configured in cups, and i can print with another module (just not images/logos).
Can someone help, please?
Thank you

**Comment by jor3l** [comment]
You will have to debug your USB devices, probably the printer is showing up with a different ID than the ones in the code causing the not found error

**Comment by natsu90** [comment]
Hi, how do I debug this? The printer is working fine when in MacOSX but not in RPi.

**Comment by jor3l** [comment]
Sudo works on my RPi

**Comment by song940** [comment]
Did you solve the problem ? @natsu90

**Comment by natsu90** [comment]
I just need to tighten up the usb, that's it.

**Comment by song940** [comment]
<img width="435" alt="screen shot 2016-11-01 at 13 36 46" src="https://cloud.githubusercontent.com/assets/1323768/19880455/484f613c-a038-11e6-8d77-5a32ea3f0649.png">

@natsu90
