### ISSUE TITLE
Suggestions for version-specific release archives

### ISSUE THREAD

**Issue by uyu423** [song940/node-escpos#61]
The current version of `escpos` is still being updated, but the number in the release tab of the repository is zero. I think it's a good idea to use releases and tags when certain versions are fixed. 

When the version is fixed, the release update, including the tag and the update history, has a great advantage in checking the update history later.

I would like to hear comments on this issue.

**Comment by song940** [comment]
Good suggestion, I agree.

**Comment by uyu423** [comment]
@song940  good. I expect you to generate tags and releases the next time you deploy.
