### ISSUE TITLE
I think we need a global character encoding setting method.

### ISSUE THREAD

**Issue by uyu423** [song940/node-escpos#69]
Recently there are a lot of encoding settings and related issues.

I also use the EUC-KR encoding setting, but it is inconvenient to put the encoding setting in the second parameter of the `Printer.text()` method each time.

So I think we need a global prototype method to set the encoding.

If you do so, the code will be simpler to use with the `Printer.text()` method, and if you add encode to the example, you expect that encoding-related issues will be reduced.

It's simple code and logic that I think in my head.

```javascript
function Printer(adapter){
  // https://github.com/song940/node-escpos/blob/master/printer.js#L17
  // ...
  this.adapter = adapter;
  this.buffer = new Buffer();
  this.encoding = 'GB18030';
};

// ...
Printer.prototype.text = function(content, encoding){
  // https://github.com/song940/node-escpos/blob/master/printer.js#L101
  return this.print(iconv.encode(content + _.EOL, encoding || this.encoding));
};

// ...
Printer.prototype.encode = function(encoding) {
  this.encoding = encoding;
  return this;
}
```

Perhaps I will soon be writing a pull request, but I'd like to get a developer review before that. Are there any things you need to supplement this code, or should you be careful about using buffers?

**Comment by song940** [comment]
Good ieda!
