### ISSUE TITLE
打印出来乱码中文也没有支持！能告诉是什么问题么！

### ISSUE THREAD

**Issue by bacel12596** [song940/node-escpos#72]
`const escpos = require('../');
const device  = new escpos.Network('192.168.0.101');
const printer = new escpos.Printer(device);
console.log(printer);

device.open(function(err){

  printer
  .font('a')
  .align('ct')
  .style('bu')
  .size(1, 1)
  .text('The quick brown fox jumps over the lazy dog')
  .text('敏捷的棕色狐狸跳过懒狗')
  .barcode('1234567', 'EAN8')
  .qrimage('https://github.com/song940/node-escpos', function(err){
    this.cut();
    this.close();
  });
});`

![qq 20170902202205](https://user-images.githubusercontent.com/15759967/29995472-70f55428-901c-11e7-90ce-eaf0643b8175.jpg)

**Comment by bacel12596** [comment]
二维码也没有

**Comment by bacel12596** [comment]
麻烦，可以告诉我么

**Comment by uyu423** [comment]
I think you should check the specifications of the printer you are using. Does the printer support Chinese character encoding settings and 2D barcode printing?

**Comment by Psychopoulet** [comment]
o_O
how do you think we can help you writing in a non-english way ? why not in cyrillic ? ^^

whatever, I agree with uyu, but you can test first with an encodage enforcement (encode("encodeType"))

**Comment by song940** [comment]
Check encoding of your printer supports.

In chinese:

现在还有问题吗？检查下你的打印机编码。

**Comment by bacel12596** [comment]
已经好了谢谢！ ok  thank you

**Comment by song940** [comment]
How did you solved it ?

In chinese:

普通打印和二维码都没问题了？你怎么解决的？
你有修改代码吗？如果有欢迎 PR 给我。
