### ISSUE TITLE
LPT support

### ISSUE THREAD

**Issue by zhanghuanchong** [song940/node-escpos#75]
Does it support  LPT1 on Windows? I tried to use "LPT1" as port for SerialPort, failed. No action. 

Please help.

**Comment by uyu423** [comment]
We are using [node-serialport](https://github.com/EmergingTechnologyAdvisors/node-serialport
) as a serial port communication library. Checking the specification of node-serialport does not seem to support LPT communication. For LPT communication, it seems that you need to use additional library such as [node-lpt](https://github.com/shemanaev/node-lpt). Currently, there is no way to communicate with LPT.

**Comment by song940** [comment]
Escpos supports usb, serialport and network for now.
