### ISSUE TITLE
React native ?

### ISSUE THREAD

**Issue by ax88** [song940/node-escpos#76]
Does it support react native ?

**Comment by uyu423** [comment]
I am not react-native but I am using it well in electron. React-native also seems to be available if module rebuild works well.

**Comment by ricardocjca** [comment]
I tried to do with electron, but to get lost in the zadig installation, I love the printer driver without the driver and driver, now the printer driver is a serial bus device, I do not know if I did it right, it's like me help I can not run the example.

**Comment by uyu423** [comment]
@ricardocjca 
I was not good at using serial port communication. Nevertheless, if you want to use the serial port, make sure that the COM port setting is correct. Many printers may need to install additional driver files to configure the COM port. 

I used POSBANK's A7 printer and had to install the serial port driver. Please refer to the printer manufacturer's website you are using.

I think it's better to do USB communication and install zadig. When I used serial port communication it was very unstable.

**Comment by song940** [comment]
You can expose printer to network and use network adapter in react native .

**Comment by brkrtp** [comment]
+1 ı want to using react native esc pos only network module, but ı dont have idea how its work...
