### ISSUE TITLE
Is it possible to add 'disconnect' event or automatically try to reconnect?

### ISSUE THREAD

**Issue by jor3l** [song940/node-escpos#8]
I'm working on a POS using this module but there is no way so far that I can reliably detect when the printer is disconnected, is it possible to add such events? maybe along the device.open callbacks (new callback for close).

Thank you for your amazing work :)

**Comment by jor3l** [comment]
Implemented on my fork ;)

**Comment by song940** [comment]
@jor3l pull-request are welcome .
