### ISSUE TITLE
Any specification for other brand POS printer ? My printer work only English character.

### ISSUE THREAD

**Issue by chanai-m** [song940/node-escpos#88]
Hello,
I'm using GPrinter / Model GP-58MB which is supported ESC/POS commands. And supported Chinese, Korea, etc. languages.
You can refer. to here http://www.gprinter.hk/pos-printers-58mb.html
And i try brought a printer to test on real POS system that can print receipt multiple language and work fine.

But from sample only English characters printout other will be print as unreadable characters.

MacOS Sierra 10.12.6
NodeJS v8.9.0
![asset](https://user-images.githubusercontent.com/422027/32290043-60023aa4-bf6b-11e7-82ca-9fa3d1ef8916.jpg)

**Comment by fanchou** [comment]
@MonkeyDoll Maybe your code clashes with baudRate of printer

**Comment by uyu423** [comment]
please check character encoding set

**Comment by MonkeyDoll** [comment]
@fanchou If that is the case, how to solve baudRate issue ?

@uyu423 Do you mean encoding on printer/hardware's setting ? Or script level ? 
If it's a script level's issue, I using sample code it mean that sample code has issue right ?

**Comment by fanchou** [comment]
@MonkeyDoll Read the instruction，how to change baudRate.  the printer >= your code set(9600)

![wechatimg389](https://user-images.githubusercontent.com/2160502/33109247-6f6cffc2-cf7b-11e7-8e4e-e2f1dad01c91.jpeg)

**Comment by Psychopoulet** [comment]
any question now ?

**Comment by komikoni** [comment]
When not in kanji mode,
It is necessary to execute the start command of kanji mode.
(In most cases, once you run it, the state of kanji mode will be remembered)

```javascript
// Select Kanji character mode
await printer.print('\x1c\x2e') // FS .
// Cancel Kanji character mode
await printer.print('\x1c\x26') // FS &
```

**Comment by monajafi** [comment]
I have the same issue with BeiYANG BTP-2002NP model the printer just prints english characters
what is the solution around this

**Comment by Psychopoulet** [comment]
you can test all the encodings until you found the good  one.
are you sure that your printers supports kanjis ? (... kata, katakana, cyrillic, whatever you want)

**Comment by monajafi** [comment]
I ended up delegating print job to C# console code. this library's print speed is lower than direct print

**Comment by song940** [comment]
Any questions?
