### ISSUE TITLE
How to use Network adapter?

### ISSUE THREAD

**Issue by pineapple507** [song940/node-escpos#9]
I changed a few lines of code, but I don't get it to work with an IP and Port? how i'm supposed to make it work?

**Comment by ArifADS** [comment]
+1

**Comment by jor3l** [comment]
Did you try opening a TCP connection to the wifi printer? then send the same commands, I was about to work on this but I don't have a WiFi printer to test, if you do, please let me know and maybe we can get this to work together

**Comment by ArifADS** [comment]
I have not send the same commands, I have just send to it Text

**Comment by jor3l** [comment]
@arifads do you have a wifi printer we can test?

**Comment by ArifADS** [comment]
Yes I do, at the office, I have sent to it text and some raw commands like double height or cut. But is kinda pita to do it that way.

**Comment by jor3l** [comment]
If you want we can try to get it working, I have Bluetooth printer and USB working so far

**Comment by song940** [comment]
@pineapple507  Not implemented yet .

**Comment by stefano-DM** [comment]
@jor3l how did you make the bluetooth printer work? thanks

**Comment by zhaixiaoou** [comment]
@jor3l  how to connect the bluetooth printer?  Whether to use Serial Adapter? What is Serial Port? thanks!!!!

**Comment by jor3l** [comment]
@stefano-DM @zhaixiaoou I got BT printer working for Cordova apps using the https://github.com/don/cordova-plugin-ble-central plugin. Basically I'm sending the same commands as this component does once I'm connected to the BT printer. Sorry for the late response.
