### ISSUE TITLE
win7-x64  LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by sevenzhou1218** [song940/node-escpos#96]
Can you help me resolve this problem? thx

![1](https://user-images.githubusercontent.com/6635234/33706510-5a40e9e2-db6f-11e7-9c29-84cfe7df6cc6.png)

**Comment by sevenzhou1218** [comment]
I logged in as Administrator and used powershell/cmd with "run as administrator".

**Comment by song940** [comment]
You can referred to https://github.com/tessel/node-usb/issues?utf8=✓&q=LIBUSB_ERROR_ACCESS
