### ISSUE TITLE
Euro symbol

### ISSUE THREAD

**Issue by phate82** [song940/node-escpos#97]
Hi,
what encode parameter should I use to print the Euro symbol (€)?
Thanks

**Comment by Psychopoulet** [comment]
try cp863 ?

**Comment by phate82** [comment]
Hi,

thanks for your answer. I tried cp863, but a question mark is printed instead of € sign.
Any idea? Thanks again

Best regards.

**Comment by Psychopoulet** [comment]
verify your printer's encoding, it may not support this one
I use cp863, which works fine with € and french accents

**Comment by song940** [comment]
@phate82 any questions right now ?

**Comment by Elytum** [comment]
Hi ! It appears that I'm not the only one with that problem. I tested both Cp863 and Cp858 and none works. By the way Cp863 does include the symbol (https://en.wikipedia.org/wiki/Code_page_858 -> 0x20AC) but Cp858 don't (https://en.wikipedia.org/wiki/Code_page_863), are you sure it works despite of that ?

Here's the code I used to generate a ticket (Hex code also, in case the copy/pasted character was wrong):

`printer.text('€', 'Cp863');
printer.text(String.fromCharCode(0x20AC), 'Cp863');
printer.text('€', 'Cp858');
printer.text(String.fromCharCode(0x20AC), 'Cp858');`

And here's the result:
![37488855_279387232652709_4216156669047996416_n](https://user-images.githubusercontent.com/7513527/44179481-6b28c380-a0f7-11e8-8771-2e94bcf0e6a8.jpg)

Any idea why ? Thanks !

**Comment by Psychopoulet** [comment]
not "Cp863" but "cp863".
personnaly, I put a global encodate (const printer = new escpos.Printer(device); printer.encode("cp863");) to avoid to set it at each "printer.text"

**Comment by Elytum** [comment]
Maj doesn't seem to do anything, I've got the exact same ticket with or without it. And yes, I encode globally but I wrote it inside the printer.text call in order to simplify the copy/pasted code.

**Comment by Psychopoulet** [comment]
so your printer does not support this encoding, I guess. try another one, which support €, like utf8

**Comment by Elytum** [comment]
The weird thing is that I've got a ticket printed by that printer containing the € character (Using text, not images) and the self-test does list "PC858".

**Comment by MLDMoritz** [comment]
CP858 contains EUR Symbol on D5 / 0x20AC. It works fine when printing code pages. The character displayed does not match any char on the code page. The last char (wonky F) of @Elytum is what get's printed at my printer too (TH230):

Theres probably a deeper issue? Did you get it resolved?

Update: To set the codepage 6 / PC858 in the TH230 Printer you have to do following:

`printer.print(new Buffer([0x1B, 0x74, 0x06]));`

![image](https://user-images.githubusercontent.com/46711821/157893281-699f6bd0-0ea9-4afd-ac44-c2ff9d07bba9.png)

Update: Simply use `.setCharacterCodeTable(6)`...
