### ISSUE TITLE
What About Beep Sound ?

### ISSUE THREAD

**Issue by ozgursel** [song940/node-escpos#99]
I am trying to add beep functionalty..

am still searching..

> If it is Epson ESC/POS, you can try sending an ASCII BEL (Hex value 0x07) without any other characters. It is not recommended by Epson, but it might work.

[ESC/POS COMMANDS](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=72)

**Comment by song940** [comment]
em.., My terminal printer does not have buzzer, and ... pull-request are welcome 😄

**Comment by ozgursel** [comment]
```
ASCII      ESC   B     n   t
HEX        1B    42    n   t
Decimal    27    66    n   t
```
1<=n<=9,1<=t<=9

• "**n**" Refers to the number of buzzer times.
• "**t**"  Refers to the buzzer beeps every few hours (t * 100) milliseconds.

am on it...

**Comment by ozgursel** [comment]
#120
